apiVersion: v2
name: haproxy-loadbalanced-redis
description: A Helm chart for running a loadbalanced Redis cluster with HAProxy
type: application
version: 1.0.13
maintainers:
  - name: Jorijn Schrijvershof
    email: jorijn@jorijn.com
dependencies:
  - name: haproxy
    repository: https://haproxytech.github.io/helm-charts
    version: ~1.20.0
    condition: haproxy.enabled
  - name: redis
    version: 18.11.1
    repository: https://charts.bitnami.com/bitnami
