apiVersion: v2
name: haproxy-loadbalanced-redis
description: A Helm chart for Kubernetes
type: application
version: 0.1.2
maintainers:
  - name: emilweth
    email: coucou@emi.cool
dependencies:
  - name: haproxy
    repository: https://haproxytech.github.io/helm-charts
    version: 1.17.5
    condition: haproxy.enabled
  - name: redis
    version: 17.17.1
    repository: https://charts.bitnami.com/bitnami
