{{- $fullName := include "mastodon.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    # {{- if .Values.ingress.streaming.useFastlyIP.enabled }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
        set $new_client_ip $remote_addr;
        if ($http_fastly_client_ip != "") {
          set $new_client_ip $http_fastly_client_ip;
          proxy_set_header X-Real-IP $new_client_ip;
          proxy_set_header X-Forwarded-For $new_client_ip;
        }
    # {{- end }}
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
  name: {{ $fullName }}-streaming
spec:
  ingressClassName: {{ .Values.ingress.streaming.ingressClassName }}
  rules:
    - host: {{ .Values.ingress.streaming.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "mastodon.fullname" . }}-streaming
                port:
                  number: 4000
            path: /api/v1/streaming
            pathType: ImplementationSpecific
  tls:
    {{ .Values.ingress.streaming.tls | toYaml | nindent 4 }}
