apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "mastodon.fullname" . }}-high-priority
value: 1000000
globalDefault: false
description: "This priority class should be used for web service pods only."
