apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aoderelay.fullname" . }}
  labels:
    {{- include "aoderelay.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "aoderelay.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.aoderelay.prometheusEndpoint }}
        {{- if .Values.aoderelay.prometheusEndpoint.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.aoderelay.prometheusEndpoint.port | quote }}
        {{- end }}
        {{- end }}
      labels:
        {{- include "aoderelay.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aoderelay.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          envFrom:
            - configMapRef:
                name: {{ include "aoderelay.fullname" . }}-config
            - secretRef:
                name: {{ include "aoderelay.fullname" . }}-secret-env
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "aoderelay.fullname" . }}-pvc
              mountPath: {{ .Values.aoderelay.sledPath }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "aoderelay.fullname" . }}-pvc
          persistentVolumeClaim:
            claimName: {{ include "aoderelay.fullname" . }}-pvc
